# Generated by Django 5.2.6 on 2025-09-06 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('dashboard', 'Data Dashboard'), ('map', 'Map Visualization'), ('table', 'Data Table'), ('alert', 'Alert System'), ('form', 'Data Entry Form'), ('report', 'Report Generator'), ('generic', 'Generic Page')], max_length=20)),
                ('description', models.TextField()),
                ('template_content', models.TextField()),
                ('required_libraries', models.JSONField(blank=True, default=list)),
                ('css_template', models.TextField(blank=True)),
                ('js_template', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('user_request', models.TextField()),
                ('html_content', models.TextField(blank=True)),
                ('generation_prompt', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('generation_time_seconds', models.FloatField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_sources_used', models.ManyToManyField(blank=True, to='datasets.datasource')),
                ('template_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.htmltemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField()),
                ('processed_request', models.TextField(blank=True)),
                ('llm_provider', models.CharField(default='openai', max_length=50)),
                ('model_used', models.CharField(blank=True, max_length=50)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.generatedpage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
