# Generated by Django 5.2.6 on 2025-09-07 08:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWhitelistStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_whitelisted', models.BooleanField(default=False)),
                ('whitelist_reason', models.CharField(blank=True, choices=[('domain', 'Whitelisted Domain'), ('email', 'Whitelisted Email'), ('manual', 'Manual Override')], max_length=50, null=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whitelist_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Whitelist Status',
                'verbose_name_plural': 'User Whitelist Statuses',
            },
        ),
        migrations.CreateModel(
            name='WhitelistedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text="Email domain without @ symbol (e.g., 'company.com')", max_length=255, unique=True)),
                ('description', models.CharField(blank=True, help_text='Optional description for this domain', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this domain is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Whitelisted Domain',
                'verbose_name_plural': 'Whitelisted Domains',
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='WhitelistedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Full email address', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('description', models.CharField(blank=True, help_text='Optional description for this email', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this email is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Whitelisted Email',
                'verbose_name_plural': 'Whitelisted Emails',
                'ordering': ['email'],
            },
        ),
    ]
