# Generated by Django 5.2.6 on 2025-09-07 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whitelistedemail',
            name='created_by',
        ),
        migrations.AddField(
            model_name='userwhiteliststatus',
            name='github_organizations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userwhiteliststatus',
            name='github_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userwhiteliststatus',
            name='whitelist_reason',
            field=models.CharField(blank=True, choices=[('organization', 'Whitelisted Organization'), ('username', 'Whitelisted Username'), ('manual', 'Manual Override')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='WhitelistedOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(help_text="GitHub organization name (e.g., 'mycompany', 'opensource-org')", max_length=255, unique=True)),
                ('description', models.CharField(blank=True, help_text='Optional description for this organization', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this organization is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Whitelisted GitHub Organization',
                'verbose_name_plural': 'Whitelisted GitHub Organizations',
                'ordering': ['organization'],
            },
        ),
        migrations.CreateModel(
            name='WhitelistedUsername',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text="GitHub username (e.g., 'johndoe')", max_length=255, unique=True)),
                ('description', models.CharField(blank=True, help_text='Optional description for this username', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this username is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Whitelisted GitHub Username',
                'verbose_name_plural': 'Whitelisted GitHub Usernames',
                'ordering': ['username'],
            },
        ),
        migrations.DeleteModel(
            name='WhitelistedDomain',
        ),
        migrations.DeleteModel(
            name='WhitelistedEmail',
        ),
    ]
